### ISSUE TITLE
ctypes, cffi provides just the same, but much more?

### ISSUE THREAD

**Issue by albertz** [ZeroIntensity/pointers.py#28]
I'm just wondering whether there is anything here which is not in ctypes or cffi.

The documentation does not mention this at all. Maybe this can be added.

**Comment by ZeroIntensity** [comment]
off the top of my head, the segfault handler cannot be recreated using cffi or ctypes, but this doesn't really make sense to say in the first place. sure, you could replicate many of this library's features using those, but one of the reasons this exists is so that you don't have to.

from developing this lib, i can tell you first hand that ctypes can be a pain in the ass to work with (especially when it comes to type safety).

you could apply this question to really anything. "why should i use a framework like fastapi or django when i can just get more out of it by handwriting a server in c?"

but even then, you could probably say back "ctypes isn't that hard to use, youre just bad" or something like that, which in that case youre forgetting that this library targets python developers who are looking to toy around with the language without having to get into the messy stuff.

i agree, if you do need a hardcore ffi, then this library isn't the right choice, but that's not why this exists. i merely wrote the bindings because nobody else (that i had seen at least) had made a type safe ffi yet. that, and it was a fun project to do.

**Comment by albertz** [comment]
You can see my question also as a request to clarify the documentation regarding that aspect. Your answer here still does not really clarify it for me. I still don't really understand it.

> you could apply this question to really anything.

If the question makes sense, i.e. some projects are related, and their difference is not totally obvious (like your lib vs ctypes), then I think it's always good to explain in the readme or documentation.

So you say your lib is easier than ctypes? In what way? Looking at your examples, what I remember from ctypes looks just as simple.

You say things can be replicated using ctypes or cffi? This confuses me. From the name and readme of your lib, it sounds like this is mostly about having pointers in Python. But this does not need to be replicated, it's directly there in ctypes. The code even looks similar, whether I use your lib or ctypes.

I also don't see how your lib is type safe while ctypes or cffi is not. It's just type safe in the same way, or not? At least I don't exactly understand what you mean by that.

Maybe I totally misunderstand something here, but then it would be good to better explain it in the readme.

**Comment by ZeroIntensity** [comment]
as i said, this library isnt supposed to rival ctypes or be a prod ready ffi at all. it's a toy library designed to make messing with the languages internals easier. if you want to use all of ctypes' weird things, i really don't care, that's not why i built this.

by saying "it's easier", i mean less lines of code, and how "clean" it is. i didn't think i really needed to specify "how", since it's pretty obvious (assuming youre talking about the bindings).

im not sure how you don't see the type safety problems. let's say you put a `c_int` into a `ctypes.pointer`. when you access `ptr.contents`, you have no idea what that actually is, other than just some arbitrary c type. im not saying this behavior should be changed (and it shouldn't, since something else can touch the memory of that `ctypes.pointer`, which would break type safety), but it's more just frustrating to work with for most cases.

note that ctypes also has many, many, many problems relating to how "pythonic" it is, that im not even going to get into here (and also another reason why this was built).

you seem to have some motive to attack this library for whatever reason. please remember that **this library is a toy, not a production ready ffi.** i created it as a joke in the first place, just to see if i actually could do it, and then progressed to adding more useful features over the months, but that "joke library" factor is still at the heart of this library.

**Comment by ZeroIntensity** [comment]
now one more thing, please do not take anything here personally. ive seen your projects, and you are an exceptionally talented developer. it may seem as im overreacting or something along those lines, but this is actually a really good question that ive been asked wherever several times, but the answer is just too long to give them. 

i think it's just hard for people to understand the actual nature of this library at times.

**Comment by albertz** [comment]
Yes I get that the lib started as a toy experiment, but I was just curious anyway. Of course I don't take anything personally or as an attack or anything like that. Maybe I just didn't look too closely at the lib. I'm also currently somewhat distracted with a newborn child... :)

Regarding type safety in ctypes, you have `POINTER(c_int)` as a type, where `contents` will always be a `c_int`, if I remember correctly? Or not? Or maybe it wrapped that as `int`? But then `c_int` was a special case here. I remember I needed to do some wrapper for this long time ago (search for `c_int` [here](https://github.com/albertz/PyCParser/blob/master/interpreter.py#L561)).

**Comment by ZeroIntensity** [comment]
maybe they changed it. i just remember having to put `# type: ignore` on a bunch of ctypes code

**Comment by albertz** [comment]
Ah, that's what you mean by type safety. So just checking the types in mypy or whatever you use? But the actual types should be correct.

https://github.com/python/mypy/issues/7540 is maybe about that? When you google mypy + ctypes, a couple of things show up.

**Comment by ZeroIntensity** [comment]
how would this work with function pointers?
