### ISSUE TITLE
Uses Cython implementation details

### ISSUE THREAD

**Issue by Gloweye** [ZeroIntensity/pointers.py#3]
The way this library gets the memory addresses (the `id()` builtin) isn't valid in all versions of python. It's a Cython implementation detail that it actually points towards the memory address - the only guarantee across implementations is that the value is unique. 

For reference: https://docs.python.org/3/library/functions.html#id

**Comment by ZeroIntensity** [comment]
interesting, do you know if something like `ctypes.addressof` would work better?

**Comment by Dunes** [comment]
There's no point trying to support Python implementations that do not use an object's memory address for `id()`. The reason for this, is that those implementations cannot guarantee a memory address will be constant and unique for the lifetime of an object, so they provide some other value as an id. These implementations choose some other value for an object's id because they move object's around in memory for some reason (eg. Jython doing garbage collection).

**Comment by Gloweye** [comment]
It's theoretically possible for a descriptor-protocol-like thing to exist specifically to remember memory addresses regardless of implementation (and updating on move), but I wouldn't expect it to actually exist. 

And just keeping an object reference to dynamically call something along the lines of `ctypes.addressof` would very much break the spirit of this package.

**Comment by ZeroIntensity** [comment]
theres, not much i can do about this, closing.

**Comment by JesseTG** [comment]
Perhaps as a compromise you could throw an exception if this monstrosity is running on somethings besides Cython? You know, failing gracefully.
